# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-09 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170804_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture_details',
            options={'verbose_name': '\u56fe\u7247\u8be6\u60c5', 'verbose_name_plural': '\u56fe\u7247\u8be6\u60c5'},
        ),
    ]
